include: package:lints/recommended.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - test/**

custom_lint:
  # All clean_architecture_linter rules are enabled by default.
  # Only configure rules that need specific settings.

  # Optional: Enable test coverage checks
  # rules:
  #   - clean_architecture_linter_require_test: true
  #     check_usecases: true
  #     check_repositories: true
  #     check_datasources: true
  #     check_notifiers: true