name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: ['3.2.0', 'stable']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Dart SDK
      uses: dart-lang/setup-dart@v1
      with:
        sdk: ${{ matrix.sdk }}

    - name: Print Dart SDK version
      run: dart --version

    - name: Install dependencies
      run: dart pub get

    - name: Verify dependencies
      run: dart pub deps

    - name: Run analyzer
      run: dart analyze --fatal-infos

    - name: Check formatting
      run: dart format --output=none --set-exit-if-changed .

    - name: Run tests
      run: dart test

    - name: Check pub publishing
      run: dart pub publish --dry-run

  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Dart SDK
      uses: dart-lang/setup-dart@v1
      with:
        sdk: 'stable'

    - name: Install dependencies
      run: dart pub get

    - name: Install coverage tools
      run: dart pub global activate coverage

    - name: Run tests with coverage
      run: dart test --coverage=coverage

    - name: Convert coverage to LCOV
      run: dart pub global run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --report-on=lib

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: coverage/lcov.info
        flags: unittests
        name: codecov-umbrella

  example-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Dart SDK
      uses: dart-lang/setup-dart@v1
      with:
        sdk: 'stable'

    - name: Install main package dependencies
      run: dart pub get

    - name: Verify example structure
      run: |
        echo "Checking example files..."
        ls -la example/lib/good_examples/ || echo "Good examples directory"
        ls -la example/lib/bad_examples/ || echo "Bad examples directory"
        echo "✅ Example structure verified"