name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  # Run all quality checks before publishing
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Dart SDK
      uses: dart-lang/setup-dart@v1
      with:
        sdk: 'stable'

    - name: Install dependencies
      run: dart pub get

    - name: Verify dependencies
      run: dart pub deps

    - name: Run analyzer
      run: dart analyze --fatal-warnings

    - name: Check formatting
      run: dart format --line-length=120 --output=none --set-exit-if-changed .

    - name: Run tests
      run: dart test

    - name: Check pub publishing (dry run)
      run: dart pub publish --dry-run

  # Publish only if tests pass
  publish:
    needs: test
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1